### ISSUE TITLE
Issue with starting the node server.js

### ISSUE THREAD

**Issue by KamielV** [enreeco/heroku-crest#1]
Hi, whenever I try to start the app I get this error in the log. Do you know what can cause this problem?

2018-02-28T12:52:15.424227+00:00 heroku[web.1]: Starting process with command `node server.js`
2018-02-28T12:52:18.645736+00:00 heroku[web.1]: Process exited with status 1
2018-02-28T12:52:18.660286+00:00 heroku[web.1]: State changed from starting to crashed
2018-02-28T12:52:18.582213+00:00 app[web.1]: util.js:948
2018-02-28T12:52:18.582241+00:00 app[web.1]:     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'Function');
2018-02-28T12:52:18.582243+00:00 app[web.1]:     ^
2018-02-28T12:52:18.582245+00:00 app[web.1]: 
2018-02-28T12:52:18.582246+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function
2018-02-28T12:52:18.582248+00:00 app[web.1]:     at Object.inherits (util.js:948:11)
2018-02-28T12:52:18.582250+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/spdy/lib/spdy/server.js:297:6)
2018-02-28T12:52:18.582252+00:00 app[web.1]:     at Module._compile (module.js:662:30)
2018-02-28T12:52:18.582254+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:673:10)
2018-02-28T12:52:18.582256+00:00 app[web.1]:     at Module.load (module.js:575:32)
2018-02-28T12:52:18.582258+00:00 app[web.1]:     at tryModuleLoad (module.js:515:12)
2018-02-28T12:52:18.582259+00:00 app[web.1]:     at Function.Module._load (module.js:507:3)
2018-02-28T12:52:18.582261+00:00 app[web.1]:     at Module.require (module.js:606:17)
2018-02-28T12:52:18.582262+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-02-28T12:52:18.582265+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/spdy/lib/spdy.js:31:15)

**Comment by KamielV** [comment]
I found the issue, in node_modules\spdy\lib\spdy\server.js on line 297: util.inherits(Connection, process.EventEmitter); is depricated. You should use util.inherits(Connection, require('events')); instead.
